[package]
name = "foo"
description = "An example package"
homepage = "https://github.com/foo-cpp/foo"
repository = "https://github.com/foo-cpp/foo"
documentation = "https://readthedocs.io/foo"
maintainers = ["J. Random Hacker <jrh@cs.cmu.edu>"]
license = "MIT/Apache-2.0"
build-system = "gnu-build-system"

[version."0.1.0".source]
git = "https://github.com/foo-cpp/foo.git"
rev = "abcdef0123456789"

[version."0.2.0".source]
git = "https://github.com/foo-cpp/foo.git"
rev = "abcdef0123456789"

[features]
default = []
with-bzip2 = [
    "bzip2",
    "gnu-build-system/with-bzip2",
    "gnu-build-system/enable-compression=bzip2"
]

[dependencies]
bzip2 = { version = "1.0.0", optional = true, reason = "For compression" }

[gnu-build-system]
cxxflags = ["-Wall", "-std=c++11"]
working-dir = "./project"

[post-install.copy]
"./project/config.toml" = ["/etc/foo/"]
