[package]
name = "foo"
description = "An example package"
homepage = "https://github.com/foo-rs/foo"
repository = "https://github.com/foo-rs/foo"
documentation = "https://docs.rs/foo"
maintainers = ["J. Random Hacker <jrh@cs.cmu.edu>"]
license = "MIT/Apache-2.0"
build-system = "cargo-build-system"

[version."0.1.0".source]
git = "https://github.com/foo-rs/foo.git"
rev = "abcdef0123456789"

[version."0.2.0".source]
git = "https://github.com/foo-rs/foo.git"
rev = "abcdef0123456789"

[features]
default = []
with-bzip2 = [
    "crates-io.bzip2",
    "cargo-build-system/with-bzip2",
]

[dependencies]
crates-io.bzip2 = { version = "1.0.0", optional = true, reason = "For compression" }

[cargo-build-system]
profile.release.debug-assertions = true

[post-install.copy]
"./project/config.toml" = "/etc/foo/"
"./target/release/foo" = "/bin/foo"
